use loco_inertia::Inertia;
use loco_rs::{
    controller::views::pagination::PagerMeta,
    model::query::{PageResponse, PaginationQuery},
    prelude::*,
};
use serde::Serialize;

const PAGE_SIZE: usize = 8;

#[derive(Clone, Copy, Serialize)]
struct Episode {
    number: u16,
    title: &'static str,
    runtime: &'static str,
}

const EPISODES: [Episode; 291] = [
    episode(1, "Mini-Goku is an Overprotected Boy! I am Gohan", "22 min"),
    episode(2, "The Mightiest Warrior in All of History is Goku's Older Brother!", "22 min"),
    episode(3, "All Right! This is the Strongest Combo in the World!", "22 min"),
    episode(4, "Piccolo's Trump Card! Gohan, the Crybaby-kun", "22 min"),
    episode(5, "Goku Dies! There's Only One Last Chance", "22 min"),
    episode(6, "Even Yama-sama is Surprised -- The Fight Continues in the Next World", "22 min"),
    episode(7, "Survival with Dinosaurs! Gohan's Harsh Training", "22 min"),
    episode(8, "A Great Transformation on a Moonlit Night! The Secret of Gohan's Power", "22 min"),
    episode(9, "Sorry, Robot-san -- The Desert of Vanishing Tears", "22 min"),
    episode(10, "Don't Cry, Gohan! His First Fight", "22 min"),
    episode(11, "The Saiyans, Mightiest Warriors in the Universe, Awaken!", "22 min"),
    episode(12, "Catnap on the Serpentine Road -- Goku Takes a Tumble", "22 min"),
    episode(13, "Hands Off! Yama-sama's Secret Fruit", "22 min"),
    episode(14, "Such Sweet Temptation! The Snake Princess-sama's Hospitality", "22 min"),
    episode(15, "Escape from Piccolo! Gohan Summons a Storm", "22 min"),
    episode(16, "Run, Gohan! Longing for Mount Paozu, Where Chichi is Waiting", "22 min"),
    episode(17, "City of No Tomorrow! The Long Road to Victory", "22 min"),
    episode(18, "Last Stop on the Serpentine Road! Are you Kaio-sama", "22 min"),
    episode(19, "The Battle with Gravity! Catch Bubbles-kun", "22 min"),
    episode(20, "The Saiyan Legend Reborn! Goku's Roots", "22 min"),
    episode(21, "Come Forth, Shen Long! The Saiyans Finally Arrive on Earth", "22 min"),
    episode(22, "Unbelievable! Saibaimen, Born of the Soil", "22 min"),
    episode(23, "Yamucha Dies! The Terror of the Saibaimen", "22 min"),
    episode(24, "Farewell, Ten-san! Chaozu's Suicide Strategy", "22 min"),
    episode(25, "Tenshinhan Cries Out!! This is My Final Kikoho", "22 min"),
    episode(26, "An Intense Three-Hour Delay! The Kinto Un Bullet-Express", "22 min"),
    episode(27, "Leave it to Me! Gohan's Great Burst of Anger", "22 min"),
    episode(28, "Ferocity of the Saiyans! Kami-sama and Piccolo Both Die", "22 min"),
    episode(29, "Father is Awesome! Kaio-ken, the Ultimate Finishing Technique", "22 min"),
    episode(30, "A Hot, Unbounded Battle! Goku vs. Vegeta", "22 min"),
    episode(31, "Now, Goku! A Final Technique With Everything On the Line", "22 min"),
    episode(32, "Battle Power Times Ten!! Vegeta's Great Metamorphosis", "22 min"),
    episode(33, "Don't Die, Father!! This is the Depth of Gohan's Power", "22 min"),
    episode(34, "Shoot, Kuririn! The Genki Dama, Packed with Hope", "22 min"),
    episode(35, "Cause a Miracle! Son Gohan, the Super Saiyan", "22 min"),
    episode(36, "We're Off Into Space! The Star of Hope is Piccolo's Homeland", "22 min"),
    episode(37, "Mysterious Yunzabit! The Search for Kami-sama's Spaceship", "22 min"),
    episode(38, "Blast-off for Planet Namek! The Terror Awaiting Gohan & Co", "22 min"),
    episode(39, "Friends or Foes Children of the Mysterious Giant Spaceship", "22 min"),
    episode(40, "Honest to Goodness There Lies Namek, Planet of Hope", "22 min"),
    episode(41, "Kind-hearted Aliens. There's the Wu Xing Qiu Ball Already", "22 min"),
    episode(42, "Planet Freeza No. 79 Vegeta Recovers!!", "22 min"),
    episode(43, "The Dragon Balls Are All Found! Piccolo-san Will Also Come Back to Life", "22 min"),
    episode(44, "A Tough New Enemy! Freeza, Emperor of the Universe", "22 min"),
    episode(45, "Vegeta's Ambition! I am the Greatest Warrior in the Universe!!", "22 min"),
    episode(46, "Goku's Power Unleashed!! Six Days to the Far End of the Galaxy", "22 min"),
    episode(47, "Surprise Attack!! The Elder's Target Was the Scouters", "22 min"),
    episode(48, "Gohan in Peril! A Pursuing Dodoria Summons Death", "22 min"),
    episode(49, "Dodoria Dies by Explosion! Vegeta's Fearsome Shockwave", "22 min"),
    episode(50, "Escape From a Burning Planet!! A Life-or-Death Kamehame-Ha", "22 min"),
    episode(51, "Courage Times One Hundred! The Warriors Gathered Under Kaio", "22 min"),
    episode(52, "Listen to Me, Goku! Hands Off Freeza", "22 min"),
    episode(53, "Nothing but Goosebumps! The Handsome Warrior Zarbon's Devilish Transformation", "22 min"),
    episode(54, "Defend the Star of Hope!! Kuririn's Astonishing Power-Up", "22 min"),
    episode(55, "Back from the Brink of Death -- The Miracle Man, Vegeta", "22 min"),
    episode(56, "An Enormous Battle Power!! Freeza's Scheme is Shattered", "22 min"),
    episode(57, "I'm Back to My Old Self Again!! Goku Under 100-Times Super-Gravity", "22 min"),
    episode(58, "Freeza's Secret Weapon! The Devilish Ginyu Special Corps", "22 min"),
    episode(59, "Watch Out, Bulma!! Si Xing Qiu Falls into Freeza's Clutches", "22 min"),
    episode(60, "Charge!! The Kaio-ken and Kamehame-Ha of an Indomitable Spirit", "22 min"),
    episode(61, "The Great Battle Approaches! The Ginyu Special Corps Now Takes the Stage!!", "22 min"),
    episode(62, "Goku on Final Approach! Smash Through Freeza's Dragnet", "22 min"),
    episode(63, "Super-Magic or Just a Trick! Mr. Ghurd is Angry!", "22 min"),
    episode(64, "The Savage ReaCoom!! He's Bad, He's Strong, He's Outrageous", "22 min"),
    episode(65, "Don't Die, Gohan! Goku Finally Touches Down on the Battlefield", "22 min"),
    episode(66, "Uncommon Strength!! Son Goku, the Legendary Super Saiyan", "22 min"),
    episode(67, "Lightning Balls of Red and Blue! Jheese and Butta Attack Goku", "22 min"),
    episode(68, "At Last, a Direct Confrontation!! Commander Ginyu Takes the Field", "22 min"),
    episode(69, "Incredible Force!! Did You See Goku's Full Power", "22 min"),
    episode(70, "What of the Battle's Outcome! Freeza's Evil Hand Closes Around the Grand Elder", "22 min"),
    episode(71, "Surprise!! Goku is Ginyu and Ginyu is Goku", "22 min"),
    episode(72, "Come Forth, Super Shen Long!! Grant Me My Wish", "22 min"),
    episode(73, "That Ain't Me! Gohan, Don't Lose Your Nerve, Hit Your Father!!", "22 min"),
    episode(74, "Whoops!! Ginyu Has Turned Into a Frog", "22 min"),
    episode(75, "Thou Who Hast Gathered the Seven Balls... Now Speak Forth the Password", "22 min"),
    episode(76, "Kami-sama Also Returns to Life! Piccolo Is Resurrected by Super Shen Long", "22 min"),
    episode(77, "Birth of the Mightiest Warrior Nail and Piccolo Merge", "22 min"),
    episode(78, "A Nightmare Super-Transformation!! Freeza's Battle Power of One Million", "22 min"),
    episode(79, "Is This the End! A Brutally Transcendent Power Attacks Gohan", "22 min"),
    episode(80, "The Tide Suddenly Turned!! Piccolo, the Warrior Who Came Late", "22 min"),
    episode(81, "Piccolo's Self-Confidence! I Will Be the One to Defeat Freeza", "22 min"),
    episode(82, "Attack, Goku!! An Enraged Freeza's Second Transformation", "22 min"),
    episode(83, "Fear Me!! Freeza Does Battle with a Third Transformation", "22 min"),
    episode(84, "The Death of Dende... Come Forth! Intense, Wide-Open Power", "22 min"),
    episode(85, "How I've Waited for this Moment!!! Son Goku Revived", "22 min"),
    episode(86, "Such Regret...!! Vegeta, Pride of the Saiyans, Dies", "22 min"),
    episode(87, "The Curtain Rises over the Ultimate Battle!! I Am Going to Defeat You", "22 min"),
    episode(88, "The Two Superpowers Collide! A Fistfight Where Both Turn Serious!!!", "22 min"),
    episode(89, "Freeza's Terrible Declaration! I Will Defeat You Without Using My Hands", "22 min"),
    episode(90, "That Was No Idle Boast!! Son Goku, an Audacious, Wonderful Guy", "22 min"),
    episode(91, "Showdown!! The Embodiment of Flame in a 20-Times Kaio-ken Kamehame-Ha", "22 min"),
    episode(92, "A Super-Huge Genki Dama-- I'm Playing My Last Card!!", "22 min"),
    episode(93, "Keep the Chance Alive!! Piccolo's Suicide Support Strike", "22 min"),
    episode(94, "The Incredible Destructive Force of the Genki Dama!! Who Will Survive!", "22 min"),
    episode(95, "Transformed At Last!! Son Goku, the Legendary Super Saiyan", "22 min"),
    episode(96, "An Explosion of Anger!! Goku, Avenge Everyone's Deaths", "22 min"),
    episode(97, "The Destruction of Planet Namek! A Demonic Flash Pierces the Ground", "22 min"),
    episode(98, "I Will Be the One Who Wins... Risking Survival, a Final Attack", "22 min"),
    episode(99, "Shen Long, Run Yourself Through Space!! The Time of Namek's Destruction Draws Near", "22 min"),
    episode(100, "I Am Son Goku's Son!! Gohan Returns to the Battlefield", "22 min"),
    episode(101, "I'm Staying on This Planet!! A Final Wish Towards Victory", "22 min"),
    episode(102, "Let's Get It On!! Two Remain on a Vanishing Planet", "22 min"),
    episode(103, "Pathos of Freeza! Once He Starts Shaking, He's Unstoppable!!", "22 min"),
    episode(104, "Goku's Declaration of Victory!! As Freeza Destroys Himself", "22 min"),
    episode(105, "Freeza Defeated!! A Single Blast Packed with a Totality of Rage", "22 min"),
    episode(106, "Planet Namek's Great Explosion!! Goku Disappears into Space", "22 min"),
    episode(107, "Son Goku Survived -- The Z Warriors All Resurrected!!", "22 min"),
    episode(108, "Terrible Happenings in Heaven!! Garlic Jr. to Become Kami!", "22 min"),
    episode(109, "Black Mist of Terror...!! Everyone Turns Demonic", "22 min"),
    episode(110, "The Heavenly Realm is the Battlefield!! Piccolo Becomes Devilish Again", "22 min"),
    episode(111, "Direct Confrontation with Piccolo!! An Angry Masenko in the Heavenly Realm", "22 min"),
    episode(112, "Retrieve Everyone's Minds!! The Ultra Holy Water Resting in the Temple", "22 min"),
    episode(113, "Can't Wait Until Morning!! Kami-sama Determines a Suicidal Course of Action", "22 min"),
    episode(114, "A Battle of Extreme Measures!! Kami-sama Breaks the Covenant", "22 min"),
    episode(115, "The Ultra Holy Water Worked!! The World Awakens from Its Nightmare", "22 min"),
    episode(116, "Gohan's Brief Chance for Victory!! Blast the Makyo World", "22 min"),
    episode(117, "You're My Guy... Kuririn -- A 101st Proposal", "22 min"),
    episode(118, "That There is Earth, Papa... The Counter-Attack of Freeza, Father and Son", "22 min"),
    episode(119, "I Will Defeat Freeza... The Mysterious Youth Awaiting Goku", "22 min"),
    episode(120, "Freeza Halved by a Single Stroke!! Another Super Saiyan", "22 min"),
    episode(121, "Heya!! It's Been a While... Son Goku Returns", "22 min"),
    episode(122, "My Dad is Vegeta... Admissions of the Mysterious Youth", "22 min"),
    episode(123, "Goku's New Finishing Technique! Watch My Instantaneous Movement", "22 min"),
    episode(124, "I Will Overcome Goku!! The King of the Saiyan Warrior Race", "22 min"),
    episode(125, "License Mastery Goku's Newest Trial", "22 min"),
    episode(126, "Murderers Who Leave No Trace -- Which Ones Are the Artificial Humans!", "22 min"),
    episode(127, "The Cold-Blooded No. 20's Hideous Atrocities!! Goku's Super Transformation of Anger", "22 min"),
    episode(128, "Goku's Double-Shock!! Caught Between Illness and Adversary", "22 min"),
    episode(129, "The Might of Vegeta! The Blood of a Super Saiyan Awakens", "22 min"),
    episode(130, "No. 20's Defiant Smile... The Secret of Doctor Gero", "22 min"),
    episode(131, "A Reality More Terrifying than the Future! Trunks' Suspicions", "22 min"),
    episode(132, "Give Chase!! The Search for Doctor Gero's Mysterious Laboratory", "22 min"),
    episode(133, "And the Terror Becomes Reality... No. 17 and No. 18 Awaken", "22 min"),
    episode(134, "Too Late to Do Anything! The Ultimate Weapons to Kill Goku", "22 min"),
    episode(135, "Good Looks and Super Power! No Blind Spot on No. 18", "22 min"),
    episode(136, "Nobody Is Able to Stop Them... Is This the End of the Z Warriors!", "22 min"),
    episode(137, "Piccolo's Resolution!! The Last Measure in His Reserve", "22 min"),
    episode(138, "Walking Weapons of Mass Destruction!! The Artificial Humans Draw Near Goku", "22 min"),
    episode(139, "An Ominous Foreboding! Bulma Unveils a Mystery", "22 min"),
    episode(140, "The Discovery of an Evil Egg!! A Terrified Trunks", "22 min"),
    episode(141, "To Face an Unprecedented Foe... Birth of a Super Namekian!!", "22 min"),
    episode(142, "Kamehame-Ha! The Monster Who Possesses Goku's Ki", "22 min"),
    episode(143, "A Life Form of Evil and Destruction!! His Name Is Artificial Human Cell", "22 min"),
    episode(144, "Piccolo's Grievous Mistake! Cell Turned Loose on the City!", "22 min"),
    episode(145, "The Secret of Cell's Birth! What Lies Below the Laboratory", "22 min"),
    episode(146, "Goku Awakens to Battle! Go Beyond Super Saiyan!!", "22 min"),
    episode(147, "Hasten Your Training, Saiyans! In the Room of Spirit and Time", "22 min"),
    episode(148, "The Gekiretsu Kodan That Split the Heavens!! Piccolo vs. Artificial Human No. 17", "22 min"),
    episode(149, "How I Have Waited for This Day!! Cell's Prologue to Perfection", "22 min"),
    episode(150, "The Suicide Counterattack Proves Ineffective! Piccolo's Flame Burns Out!!", "22 min"),
    episode(151, "One Final Remaining Hope... No. 16, the Wordless Warrior, Takes Action!!", "22 min"),
    episode(152, "No. 17 Swallowed... The Transforming Cell Is a Super Gourmet", "22 min"),
    episode(153, "Tomorrow, I Am Going to Pulverize You!! Goku's Challenge", "22 min"),
    episode(154, "I Will Dispose of Everything!! A Reborn Vegeta, Father and Son, Sally Forth", "22 min"),
    episode(155, "Suddenly Full-Throttle!! The Super Power of a Radiant Vegeta", "22 min"),
    episode(156, "On Your Knees, Cell! I Am Super Vegeta!!", "22 min"),
    episode(157, "Dangerous Pride!! A Challenge to Cell's Perfect Form", "22 min"),
    episode(158, "I'm So Distraught!! Kuririn's Handiwork in Destroying No. 18", "22 min"),
    episode(159, "A Shock to the Entire Universe!! Cell's Spectacular Evolution Toward His Perfect Form", "22 min"),
    episode(160, "Battle Power Infinity!! Birth of the God of Destruction Named Cell", "22 min"),
    episode(161, "Super Vegeta in Peril!! An Absolutely Perfect Terror Closes In!!", "22 min"),
    episode(162, "Breaking Through the Boundaries of the Super Saiyan!! Trunks Summons a Storm", "22 min"),
    episode(163, "Save Your Father!! Trunks' Fury, Which Scorches Even the Heavens", "22 min"),
    episode(164, "A Future of Despair!! Trunks, the Man Who Lived Through Hell", "22 min"),
    episode(165, "Super Trunks Has a Weakness!! Cell's Shocking Bombshell Declaration", "22 min"),
    episode(166, "A Final Battle Closes In on Goku!! The Mystery of the New Tenkaichi Tournament", "22 min"),
    episode(167, "100% Ratings!! The Cell Games Call for Death with an Exclusive Live Broadcast", "22 min"),
    episode(168, "Goku and Gohan... The Hero Father and Son's Ultimate Level-Up", "22 min"),
    episode(169, "Goku's Composure! Let's Rest and Wait for the Cell Games", "22 min"),
    episode(170, "A Warrior's Rest... The Girl, the Lies, and Gohan's Resolution", "22 min"),
    episode(171, "Hidden Power!! When Gohan Was a Baby", "22 min"),
    episode(172, "Seek Out Kami-sama!! Goku's Great Instantaneous Movement", "22 min"),
    episode(173, "Dende's First Task!! The Dragon Balls Restored", "22 min"),
    episode(174, "A Hard Problem for Goku! Take Back the Dragon Balls", "22 min"),
    episode(175, "Those Who Would Challenge Cell!! The Curtain Rises on the Battle", "22 min"),
    episode(176, "Just a Moment!! The Satan Squad Goes On the Rampage", "22 min"),
    episode(177, "Fight Time, Goku!! The Ultra-Tense Cell Games", "22 min"),
    episode(178, "Direct Hit to Earth!! Cell's Extra-Large Kamehame-Ha", "22 min"),
    episode(179, "Defeat or Death! Goku's Turnabout Ploy", "22 min"),
    episode(180, "A Conclusion to the Deathmatch!! Goku's Declaration of Surrender!", "22 min"),
    episode(181, "He Who Takes Over as Strongest... His Name is Gohan", "22 min"),
    episode(182, "Become Enraged Gohan -- Call Forth Your Dormant Power", "22 min"),
    episode(183, "Teeny Menaces!! Attack of the Cell Juniors", "22 min"),
    episode(184, "The Tragic No. 16!! An Enraged Super Gohan Begins Taking Action", "22 min"),
    episode(185, "Devastating True Power!! The Cell Juniors Pulverized", "22 min"),
    episode(186, "Cell gets KO'ed!! Just 2 Super Ironfisted Blows", "22 min"),
    episode(187, "Something Amiss With Cell!! His Perfect Form Crumbles", "22 min"),
    episode(188, "Bye-Bye, Everyone!! Goku's Last Instantaneous Movement", "22 min"),
    episode(189, "A Nightmare in Broad Daylight!! The Terror Becomes Even More Perfect", "22 min"),
    episode(190, "From Goku to Gohan... The Spirit of the Father is Handed Down", "22 min"),
    episode(191, "The Battle is Over... Thank You, Son Goku", "22 min"),
    episode(192, "I'm Going to Train In the Next World!! A Smile at Parting", "22 min"),
    episode(193, "New Days... Father! I'm Hanging In There", "22 min"),
    episode(194, "One More Conclusion!! I Will Defend the Future", "22 min"),
    episode(195, "A Deep Impression!! There They Are! The Next World's Awesome Dudes", "22 min"),
    episode(196, "I'm the Best in the Next World!! Heroes of the Ages Assembled", "22 min"),
    episode(197, "Grand Kaio's World Gone Wild!! Goku Kicks Up a Whirlwind", "22 min"),
    episode(198, "Final Round of Flame!! Goku or Paikuhan!", "22 min"),
    episode(199, "Don't Let Victory Get Away!! Finish With an Ultra-Fast Kamehame-Ha", "22 min"),
    episode(200, "7 Years Since Then! Starting Today, I'm a High School Student", "22 min"),
    episode(201, "For Love and Justice -- Enter the Great Saiyaman", "22 min"),
    episode(202, "Gohan's Frantic First Date!", "22 min"),
    episode(203, "Gohan, Scramble! Save Videl!!", "22 min"),
    episode(204, "A Case of Robbery!! The Culprit is Saiyaman!", "22 min"),
    episode(205, "Goku Returning to Life! Entry into the Tenkaichi Tournament!!", "22 min"),
    episode(206, "Even Gohan is Surprised! Goten's Explosion of Power", "22 min"),
    episode(207, "Ah, You're Flying!! Videl's Introduction to Bukujutsu", "22 min"),
    episode(208, "Welcome Back, Goku! The Entire Z Team Assembles!!", "22 min"),
    episode(209, "Watch Out, Saiyaman! Beware Of Snapshooters!", "22 min"),
    episode(210, "No Small Matter!! Little Trunks", "22 min"),
    episode(211, "It's My Turn! Goten's Anxious First Fight", "22 min"),
    episode(212, "Happiness Times A Million! The Junior Champion is Decided!!", "22 min"),
    episode(213, "Now What, Satan! The Greatest Pinch in History", "22 min"),
    episode(214, "Event Match-ups Decided!! Let's Hurry and Hold the First Round", "22 min"),
    episode(215, "What's the Matter, Piccolo! An Unheard-of No-Fight-Forfeit", "22 min"),
    episode(216, "Undyingly Unpleasant! The Mystery of Spopovitch", "22 min"),
    episode(217, "A Tragic Videl!! Are You Coming Out, Angry Super Gohan", "22 min"),
    episode(218, "Exposed!! The Saiyaman is Son Gohan", "22 min"),
    episode(219, "A Slithering Conspiracy!! Gohan's Power is Stolen", "22 min"),
    episode(220, "The Man Behind the Curtains Appears!! The Evil Madoshi Babidi", "22 min"),
    episode(221, "The Awaiting Trap!! A Challenge from the Demon Realm", "22 min"),
    episode(222, "Don't Toy With Me!! Vegeta's Breakthrough First Strike of Fury", "22 min"),
    episode(223, "Goku's Power Wide Open!! Blow Away Yakon", "22 min"),
    episode(224, "A Great Miscalculation!! Satan vs. Three Super-Warriors!", "22 min"),
    episode(225, "Such Strong Kids!! No. 18's Close Fight!", "22 min"),
    episode(226, "Confrontation with the Demon King! It's Your Turn, Gohan!!", "22 min"),
    episode(227, "A Wicked Heart Discovered!! Dabura's Great Idea", "22 min"),
    episode(228, "Vegeta, Prince of Destruction, Revived!! Intrusion at the Tournament", "22 min"),
    episode(229, "The Super-confrontation of Destiny!! The Clash of Goku vs. Vegeta", "22 min"),
    episode(230, "Just You Wait, Babidi!! Your Aspirations Will Not Be Allowed", "22 min"),
    episode(231, "The Seal is Broken! Out Comes the Vicious Majin Boo!!", "22 min"),
    episode(232, "I Won't Allow the Revival!! A Kamehame-Ha of Resistance", "22 min"),
    episode(233, "A Straight Line to Despair! The Grief of Kaioshin", "22 min"),
    episode(234, "The Terrifying Majin!! Death's Dread Draws Near Gohan", "22 min"),
    episode(235, "'Gonna Eat'cha!!' A Hungry Majin's Supernatural Power", "22 min"),
    episode(236, "A Warrior's Resolution!! I Will Dispose Of the Majin", "22 min"),
    episode(237, "For Those Whom He Loves... Vegeta Perishes!!", "22 min"),
    episode(238, "The Nightmare Revisited!! Majin Boo Has Survived", "22 min"),
    episode(239, "The Struggle of Videl and the Others! Find the Dragon Balls", "22 min"),
    episode(240, "Enormous Hope!! A New Finishing Technique for the Little Squirts", "22 min"),
    episode(241, "Goten and Trunks-- The World's Most Wanted", "22 min"),
    episode(242, "Gohan Revived -- Kaioshin's Secret Weapon!", "22 min"),
    episode(243, "It Came Ou~t!! The Legendary Z-Sword", "22 min"),
    episode(244, "Metro West is Targeted! Stop, Majin Boo!!", "22 min"),
    episode(245, "An Astounding, Great Transformation!! Super Saiyan 3", "22 min"),
    episode(246, "Bye Bye Babidi!! Majin Boo Rebels", "22 min"),
    episode(247, "Absurdly Awful-Looking! The Special Training Transformation Pose", "22 min"),
    episode(248, "See You Later, Everybody!! Goku Returns to the Other World", "22 min"),
    episode(249, "Where is Gohan! Ferocious Training in the Kaioshin Realm", "22 min"),
    episode(250, "You're Kidding, Right! The Z-Sword is Broken", "22 min"),
    episode(251, "Birth of a Superhuman Warrior!! His Name is Gotenks", "22 min"),
    episode(252, "The Final Weapon is Engaged! Satan Will Save the Earth", "22 min"),
    episode(253, "I've Stopped Killing!! Majin Boo's Good Boy Declaration", "22 min"),
    episode(254, "Run Away, Satan!! An Angry Majin Boo Emerges", "22 min"),
    episode(255, "Which One Will Win! A Good-and-Evil Boo-Boo Confrontation", "22 min"),
    episode(256, "A No-Timeout Catastrophe!! Earth's Humanity Exterminated", "22 min"),
    episode(257, "The Special Training Is a Success!! You're Finished Now, Majin Boo", "22 min"),
    episode(258, "'I'm Going Like I Mean It!!' A Wide-Open Super Gotenks", "22 min"),
    episode(259, "'I've Done It!!' Boo Successfully Eliminated With Ghosts!", "22 min"),
    episode(260, "Escape From Another Dimension!! Super Gotenks 3", "22 min"),
    episode(261, "Going Too Far! Boo-Boo Volleyball", "22 min"),
    episode(262, "Truly 'Great'!! A Reborn Gohan Returns to Earth", "22 min"),
    episode(263, "Boo Overwhelmed!! Gohan's Miracle Power", "22 min"),
    episode(264, "Has He Done It! Majin Boo's Great Explosion", "22 min"),
    episode(265, "Boo's Worst Foul!! Gotenks is Absorbed!", "22 min"),
    episode(266, "For the Sake Of the Entire Universe... Return to Life, Son Goku", "22 min"),
    episode(267, "The Miracle Happens Once... Will the Super Combination With Gohan Come About", "22 min"),
    episode(268, "Merged!! Vegeta's Pride And Goku's Rage", "22 min"),
    episode(269, "Magnificent Power!! Vegetto Surpasses the Ultimate", "22 min"),
    episode(270, "A Fissure Between Dimensions!! Has Boo Snapped!", "22 min"),
    episode(271, "The Ace Up Boo's Sleeve!! 'You Become a Hard Candy'!", "22 min"),
    episode(272, "A Hero Lost! Vegetto is Absorbed", "22 min"),
    episode(273, "A Demonic Maze!! What Is There Inside Boo's Belly!", "22 min"),
    episode(274, "Nightmares or Illusions! Goku and Gohan's Father-Son Confrontation", "22 min"),
    episode(275, "A Majin's Secret!! Two More Boos Inside Of Boo", "22 min"),
    episode(276, "Where Is the Exit! Escape from a Collapsing Boo", "22 min"),
    episode(277, "Earth Disappears!! Boo's Reverse-Transformation of Evil", "22 min"),
    episode(278, "Boo's Assault!! A Conclusion in the Kaioshin Realm", "22 min"),
    episode(279, "Seize the Future!! A Decisive Battle with the Universe at Stake", "22 min"),
    episode(280, "Vegeta Takes Off His Hat!! Goku, You Are No. 1", "22 min"),
    episode(281, "Pull Through, Vegeta!! One Life-Threatening Minute", "22 min"),
    episode(282, "Don't You Pick On Satan!! The Original Boo is Revived", "22 min"),
    episode(283, "Vegeta's Secret Plan!! Polunga and the Two Wishes", "22 min"),
    episode(284, "A Last Hope!! We'll Make a Huge Genki Dama", "22 min"),
    episode(285, "Ultra-Impressive!! The Genki Dama From Everyone is Finished", "22 min"),
    episode(286, "Son Goku is Strongest After All!! Majin Boo is Eliminated", "22 min"),
    episode(287, "Peace Returns!! Majin Boo, Champion of Justice!", "22 min"),
    episode(288, "You're Late, Goku! Everyone Party!!", "22 min"),
    episode(289, "Grandpa Goku! I Am Pan!!", "22 min"),
    episode(290, "I Am Oob! Now 10 Years Old, the Former Majin!", "22 min"),
    episode(291, "Even Stronger!! Goku's Dream is Super-Huge", "22 min"),
];

const fn episode(number: u16, title: &'static str, runtime: &'static str) -> Episode {
    Episode {
        number,
        title,
        runtime,
    }
}

pub fn routes() -> Routes {
    Routes::new().get("/episodes", index)
}

#[debug_handler]
async fn index(Query(pagination): Query<PaginationQuery>) -> Result<Response> {
    let total_pages = EPISODES.len().div_ceil(PAGE_SIZE) as u64;
    let current_page = pagination.page.clamp(1, total_pages);

    let response = Inertia::render("Episodes/Index")
        .props(serde_json::json!({}))
        .map_err(|err| Error::string(&err.to_string()))?
        .infinite_scroll("episodes", move || {
            let current_page = current_page as usize;
            async move {
                let start = (current_page - 1) * PAGE_SIZE;
                let end = (start + PAGE_SIZE).min(EPISODES.len());
                let rows = EPISODES[start..end].to_vec();
                Ok::<_, std::convert::Infallible>(PageResponse {
                    page: rows,
                    meta: PagerMeta {
                        page: current_page as u64,
                        page_size: PAGE_SIZE as u64,
                        total_pages,
                        total_items: EPISODES.len() as u64,
                    },
                })
            }
        });
    Ok(response.into_response())
}
